# Generated by Django 3.2.14 on 2022-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220717_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_short',
            field=models.CharField(max_length=200),
        ),
    ]
