# Generated by Django 4.0.6 on 2022-07-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220717_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='serial_number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
