# Generated by Django 4.0.6 on 2022-07-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='serial_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
