# Generated by Django 3.2.14 on 2022-07-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_description_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title_short',
        ),
    ]
